cloudevents/sdk/converters/base.py
cloudevents/sdk/converters/binary.py
cloudevents/sdk/converters/structured.py
cloudevents/sdk/event/base.py
cloudevents/sdk/marshaller.py
cloudevents/tests/test_event_from_request_converter.py
cloudevents/tests/test_event_pipeline.py
cloudevents/tests/test_event_to_request_converter.py

Updates binary encoding to handle [extensions](https://github.com/cloudevents/spec/blob/v0.2/http-transport-binding.md#3131-http-header-names) and [content-type](https://github.com/cloudevents/spec/blob/v0.2/http-transport-binding.md#311-http-content-type) per spec.
Update marshaller to handle both structured and binary formats. Previously, it would try structured first, even if the content-type did not match, and then ignore all the headers, producing very wimpy events with no data.
- Link to issue this resolves
I was too lazy to file an issue while debugging.
- What I did
I wrote a small python program using Flask to log cloud events, and to report them in a webpage. I'll be putting in in a pull request to https://github.com/knative/docs soon.
- How I did it
I used the following command …

Updates for binary encoding

---

setup.cfg

Causes markdown to render correctly on pypi.
- Link to issue this resolves
Too lazy to file an issue, AGAIN.
- What I did
Added long-description-content-type to `setup.cfg`
Might as well roll this in when you tag and distribute an 0.2.2 release.

Add content-type for long-description.

---

cloudevents/sdk/event/v01.py
cloudevents/sdk/event/v02.py

- Link to issue this resolves
- What I did
Fixed a typo in the "extensions" setter
- How I did it
Added the missing "s"
- How to verify it
- One line description for the changelog
Fixed typo in the "extensions" setter

Fix typo in extensions

---

tox.ini

Signed-off-by: Dustin Ingram <di@users.noreply.github.com>

Fix tox configuration for CI

---

cloudevents/sdk/converters/__init__.py
cloudevents/sdk/converters/binary.py
cloudevents/sdk/converters/structured.py
cloudevents/sdk/http_events.py
cloudevents/sdk/marshaller.py
cloudevents/tests/test_http_events.py

Fixes #54
from_http now marshalls with correct base event class depending on specversion. Created a converter is_binary function to givee from_http a hint as to whether given http headers is binary or not.
from_http now marshalls with correct base event class depending on specversion

Specversion toggling

---

cloudevents/sdk/http/__init__.py
cloudevents/sdk/http/event.py
cloudevents/tests/test_http_json_methods.py

Fixes #67 
to_json shorthand which effectively returns the body from the to_structured_http method
from_json which takes a json payload and returns a CloudEvent object. effectively just a structured from_http call.
Implemented to_json and from_json

Implemented to_json and from_json

---

cloudevents/sdk/event/base.py
cloudevents/tests/test_event_extensions.py
requirements/test.txt

Fixes #64, #62, #32
```python
import json
from cloudevents.sdk.http import CloudEvent, to_structured_http
attributes = {
"type": "com.example.string",
"source": "https://example.com/event-producer",
"ext1": "testval"
}
data = json.dumps({"data-key": "val"})
event = CloudEvent(attributes, data)
headers, body = to_structured_http(event)
print(body)
```
Will now print 
```
b'{"specversion": "1.0", "id": "45572bc9-4b9c-4230-9766-e4a5b180211d", "source": "https://example.com/event-producer", "type": "com.example.string", "time": "2020-07-22T07:23:17.117072+00:00", "data": "{\\"data-key\\": \\"val\\"}", "ext1": "testval"}'
```
Whereas before this change it would print non-top level extensions such as:
```
b'{"specversion": "1.0", "id": "be8e6b26-5a0a-47b7-8118-d9a6d84c181c", "source": …
```

Fixed top level extensions bug

---

cloudevents/sdk/http/__init__.py
cloudevents/sdk/http/event.py

Marshaller documentation in http had several places where
marshallers were confused with unmarshallers.

Fixed marshaller documentation typo's in http

---

README.md

Very minor PR.
- Fixes H4 to H2
- Match Sending CEs with Receiving CEs
- Update README for receiving CEs

docs: rename receiving cloudevents

---

README.md
cloudevents/http/http_methods.py
cloudevents/http/json_methods.py
cloudevents/tests/test_event_extensions.py
cloudevents/tests/test_http_events.py
samples/http-image-cloudevents/image_sample_server.py
samples/http-image-cloudevents/image_sample_test.py
samples/http-json-cloudevents/json_sample_server.py

Signed-off-by: Curtis Mason <cumason@bu.edu>
Fixes #103
changed 
```python
from_http(data, headers)
```
to 
```python
from_http(headers, data)
```
Did this quality of life change because many python http libraries expect headers before data, and methods such as `to_binary` return a tuple: (headers, data). It's easier to keep header first ordering consistent across methods. 
from_http now takes headers as first arg

from_http now takes headers as first arg

---

cloudevents/exceptions.py
cloudevents/http/event.py
cloudevents/http/http_methods.py
cloudevents/sdk/event/base.py
cloudevents/tests/test_base_events.py
cloudevents/tests/test_http_cloudevent.py
cloudevents/tests/test_http_events.py

Signed-off-by: Curtis Mason <cumason@google.com>
Renamed exceptions
Renamed exceptions to shorter names

exception names shortened

---

CHANGELOG.md
README.md

Signed-off-by: Curtis Mason <cumason@google.com>
Changelog 1.1.0 bump

adjusted readme and changelog

---

cloudevents/sdk/event/base.py
cloudevents/tests/test_with_sanic.py
requirements/test.txt

Fixes https://github.com/cloudevents/sdk-python/issues/137

ignore datacontenttype when using to_binary()

---

cloudevents/tests/test_http_events.py
cloudevents/tests/test_with_sanic.py

CI is broken for some runs ([example](https://github.com/cloudevents/sdk-python/runs/5878276918?check_suite_focus=true)).
Error:
```
==================================== ERRORS ====================================
____________ ERROR collecting cloudevents/tests/test_http_events.py ____________
cloudevents/tests/test_http_events.py:69: in <module>
app = Sanic()
.tox/py/lib/python3.6/site-packages/sanic/app.py:60: in __init__
"Sanic instance cannot be unnamed. "
E   sanic.exceptions.SanicException: Sanic instance cannot be unnamed. Please use Sanic(name='your_application_name') instead.
____________ ERROR collecting cloudevents/tests/test_with_sanic.py _____________
cloudevents/tests/test_with_sanic.py:[22](https://github.com/cloudevents/sdk-python/runs/5878415085?check_suite_focus=true#step …
```

ci: use valid sanic instance name

---

.github/workflows/main.yml
requirements/docs.txt
requirements/publish.txt
requirements/test.txt
setup.py
tox.ini

Support Python 3.10

---

CONTRIBUTING.md
OWNERS

Fixes: https://github.com/cloudevents/sdk-python/issues/156
Signed-off-by: Doug Davis <dug@microsoft.com>

Add some CLO stuff

---

.github/workflows/pypi-release.yml
CHANGELOG.md
RELEASING.md
pypi_packaging.py

This PR finalizes migration from `master` to `main` in the repository. Closes #162 .

ci: migrate to `main` branch

---

CHANGELOG.md
cloudevents/http/util.py
cloudevents/tests/test_http_cloudevent.py

Fixes  #183
* Add the missing exception to the list
* Add more type information

fix: `_json_or_string` no longer fails on malformed unicode buffers

---

CHANGELOG.md
cloudevents/__init__.py
requirements/test.txt

Performs a release of a new stable version.

release: v1.5.0

---

CHANGELOG.md
cloudevents/conversion.py
cloudevents/exceptions.py
cloudevents/http/__init__.py
cloudevents/http/conversion.py
cloudevents/http/event.py
cloudevents/http/event_type.py
cloudevents/http/http_methods.py
cloudevents/http/json_methods.py
cloudevents/http/util.py
cloudevents/pydantic/__init__.py
cloudevents/pydantic/conversion.py
cloudevents/pydantic/event.py
cloudevents/sdk/converters/__init__.py
cloudevents/sdk/converters/binary.py
cloudevents/sdk/converters/structured.py
cloudevents/sdk/event/attribute.py
cloudevents/tests/test_backwards_compatability.py
cloudevents/tests/test_http_cloudevent.py
cloudevents/tests/test_http_conversions.py
cloudevents/tests/test_pydantic_cloudevent.py
cloudevents/tests/test_pydantic_conversions.py
cloudevents/tests/test_pydantic_events.py
requirements/test.txt
setup.py

Fixes #181 
##Implement a CloudEvent pydantic model

feat: pydantic

---

.github/workflows/pypi-release.yml
CHANGELOG.md

Closes #178.
The release pipeline is refined and now builds and publishes `wheel` and `sdist`.
There is no need for `cibuildwheel` while we do not have any OS-specific libraries or extensions to build. Pure Python wheel is the best one we should deliver.

ci: refine publishing WF

---

.github/workflows/pypi-release.yml
CHANGELOG.md
cloudevents/__init__.py
setup.py

Fixes #203.
The constraint had a teeny-tiny misprint (a missing `,` between the versions) that made it invalid.
This change is released separately as v1.6.3 and now as v1.7.1.

hotfix: Hotfix Pydantic dependency constraints.

---

.github/workflows/main.yml
CHANGELOG.md
cloudevents/__init__.py
requirements/test.txt
setup.py
tox.ini

Fixes https://github.com/cloudevents/sdk-python/issues/177
Python 3.6 is no longer officially supported (it should work though, just not tested against).

Drop python36

---

.github/workflows/main.yml
.github/workflows/pypi-release.yml
CHANGELOG.md
cloudevents/__init__.py
setup.py
tox.ini

Add official 3.11 support and build.
Bump version to 1.9.0 and perform a release.

Add Python 3.11 support

---

cloudevents/pydantic/event.py
cloudevents/tests/test_pydantic_cloudevent.py
requirements/test.txt
setup.py

Fixes #215
Adds a compatibility layer allowing to install the SDK together with pydantic v2, while still using the v1 implementation. Further improvements would be a native pydantic v2 implementation.
Allows to install the SDK together with pydantic v2.

Adds a pydantic V2 compatibility layer

---

.pre-commit-config.yaml
CHANGELOG.md
cloudevents/__init__.py
cloudevents/pydantic/v1/event.py
cloudevents/pydantic/v2/event.py
cloudevents/tests/test_pydantic_conversions.py

Fixes #228
The Pydantic v2 `__dict__` does not provide extras anymore, so making sure we're catching them using Pydantic's parent model iteration.

Fix Pydantic custom attributes 

---

.pre-commit-config.yaml
cloudevents/pydantic/__init__.py
cloudevents/pydantic/v2/event.py

The `pydantic.VERSION` variable is not a Literal expression, so mypy is unable to assert whether we're in an environment running on Pydantic V2 or V1. This results in mypy trying to follow both paths and failing with a `no-redef` error, which is silenced by the `# type: ignore` comment.
This PR improves the code quality by removing the `# type: ignore` comment and adding a `if TYPE_CHECKING` block that only imports the latest version (V2).
This was the main intent of the PR. As a bonus, this also updates the `example` kwarg to `examples`, as it is expected for Pydantic V2.
Improved Pydantic V2 typechecking support.

Pydantic v2

---

cloudevents/kafka/conversion.py
cloudevents/tests/test_kafka_conversions.py

Fixes #211 
The `content-type` attribute will violate the attribute naming rules, so the attribute has been modified to `datacontenttype`.
Converted `content-type` to `datacontenttype` for `cloudevents`.

Modified content-type to abide by attribute naming conventions for cloudevents

---

cloudevents/kafka/conversion.py

This PR fixes wrong typings and defaults of unmarshaller args in the from_* kafka conversion functions
fixed typing and defaults of unmarshaller arguments in kafka conversion functions

fix kafka unmarshaller args typing and defaults

---

.github/workflows/pypi-release.yml

An attempt to fix PyPi publishing

chore: disable attestations while we're not using trusted publishing

---

pyproject.toml

- PY38 is EOL, so let's not mention it here

fix: remove few mentions of py38

---

pyproject.toml
src/cloudevents/core/v1/__init__.py
src/cloudevents/core/v1/event.py
src/cloudevents/core/v1/exceptions.py
tests/test_core/__init__.py
tests/test_core/test_v1/__init__.py
tests/test_core/test_v1/test_event.py

The first PR towards a full rewrite of the library. What's included in this PR:
- Support for v 1.0.2 of the specs with better validation errors and full support for custom extension attributes, including their validation. 
- Full typing support
- Better documentation for each class and methods

feat: base `CloudEvent` class as per v1 specs, including attribute validation
